openapi: 3.0.0
servers:
  - url: 'localhost:8080'
info:
  title: User API
  description: openapi generate tutorial
  version: 1.0.0
tags:
  - name: user
paths:
  /api/v1/user/{id}:
    get:
      tags:
        - user
      summary: 현재 인증된 사용자의 정보를 조회해요.
      parameters:
        - name: id
          in: path
          description: "조회하려는 사용자의 ID"
          required: true
          schema:
            type: integer
            format: int64
            example: 26286
      responses:
        200:
          description: 현재 인증된 사용자의 정보를 랜딩해요.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 유저 id
          example: 234523
        nickname:
          type: string
          example: "예원"
        gender:
          type: string
          enum: ['male', 'female', 'unknown']
          default: 'unknown'
          description: '성별 (default unknown)'
      required:
        - id
        - nickname
        - gender